fclose all;close all;clear all;clc; 
i=imread('pno3.JPG');
%cam=webcam(1);
%i = snapshot(cam);
i = cat(3, medfilt2(i(:,:,1),[3 3]), medfilt2(i(:,:,2),[3 3]), medfilt2(i(:,:,3),[3 3]));
sz = size(i);ht = sz(1);wd = sz(2);
th = 0.02*ht*wd;
C = makecform('srgb2Lab');
i_Lab = applycform(i,C);
x=i_Lab(:,:,1); y=i_Lab(:,:,2); z=i_Lab(:,:,3);
L=sum(x); L=sum(L);
a=sum(y); a=sum(a);
b=sum(z); b=sum(b);
L=L/(wd*ht); a=a/(wd*ht); b= b/(wd*ht);
d=(x>L);
e=(y>a);
f=(z>b);
g=(y>z);
h=(d&e&f&g);
%h1 = cat(3,h.*double(i(:,:,1)),h.*double(i(:,:,2)),h.*double(i(:,:,3)));
h1 = double(i).*double(repmat(h,[1,1,3]));
h1 = uint8(h1);
figure;
%imshow(h1);
subplot(2,2,1); subimage(i);
subplot(2,2,2); subimage(h1);
subplot(2,2,3); subimage(h*255);
%h1 =int8(1 - int8(h));
%error = ibw.*h1;
%imshow(255*h1);
h=sum(h);
h=sum(h);
callib_offset_noflame = h;
fprintf('Make Flame\n');
%pause(20);
%i = snapshot(cam);
i = imread('f3.JPG');
i = cat(3, medfilt2(i(:,:,1),[3 3]), medfilt2(i(:,:,2),[3 3]), medfilt2(i(:,:,3),[3 3]));
i_Lab = applycform(i,C);
x=i_Lab(:,:,1); y=i_Lab(:,:,2); z=i_Lab(:,:,3);
L=sum(x); L=sum(L);
a=sum(y); a=sum(a);
b=sum(z); b=sum(b);
L=L/(wd*ht); a=a/(wd*ht); b=b/(wd*ht);
d =(x>L);
e=(y>a);
f=(z>b);
g=(y>z);
h=(d&e&f&g);
h1 = double(i).*double(repmat(h,[1,1,3]));
h1 = uint8(h1);
figure;
%imshow(h1);
subplot(2,2,1); subimage(i);
subplot(2,2,2); subimage(h1);
subplot(2,2,3); subimage(h*255);
%h1 =int8(1 - int8(h));
%error = ibw.*h1;
%imshow(255*h1);
h=sum(h);
h=sum(h);
fprintf('%d\n',h - callib_offset_noflame);
if (h - callib_offset_noflame > th)
    fprintf('FIRE DETECTED\n');
else
    fprintf('FIRE NOT DETECTED\n');
end;
clear cam;